export const AGREEMENT_LIST_REQUEST = "AGREEMENT_LIST_REQUEST";
export const AGREEMENT_LIST_SUCCESS = "AGREEMENT_LIST_SUCCESS";
export const AGREEMENT_LIST_FAIL = "AGREEMENT_LIST_FAIL";
export const AGREEMENT_LIST_RESET = "AGREEMENT_LIST_RESET";

export const AGREEMENT_CREATE_REQUEST = "AGREEMENT_CREATE_REQUEST";
export const AGREEMENT_CREATE_SUCCESS = "AGREEMENT_CREATE_SUCCESS";
export const AGREEMENT_CREATE_FAIL = "AGREEMENT_CREATE_FAIL";

export const AGREEMENT_DETAILS_REQUEST = "AGREEMENT_DETAILS_REQUEST";
export const AGREEMENT_DETAILS_SUCCESS = "AGREEMENT_DETAILS_SUCCESS";
export const AGREEMENT_DETAILS_FAIL = "AGREEMENT_DETAILS_FAIL";
export const AGREEMENT_DETAILS_RESET = "AGREEMENT_DETAILS_RESET";

export const AGREEMENT_UPDATE_REQUEST = "AGREEMENT_UPDATE_REQUEST";
export const AGREEMENT_UPDATE_SUCCESS = "AGREEMENT_UPDATE_SUCCESS";
export const AGREEMENT_UPDATE_FAIL = "AGREEMENT_UPDATE_FAIL";
export const AGREEMENT_UPDATE_RESET = "AGREEMENT_UPDATE_RESET";

export const AGREEMENT_DELETE_REQUEST = "AGREEMENT_DELETE_REQUEST";
export const AGREEMENT_DELETE_SUCCESS = "AGREEMENT_DELETE_SUCCESS";
export const AGREEMENT_DELETE_FAIL = "AGREEMENT_DELETE_FAIL";
export const AGREEMENT_DELETE_RESET = "AGREEMENT_DELETE_RESET";
