// constants/ingredientMovementConstants.js
export const INGREDIENT_MOVEMENT_LIST_REQUEST = 'INGREDIENT_MOVEMENT_LIST_REQUEST';
export const INGREDIENT_MOVEMENT_LIST_SUCCESS = 'INGREDIENT_MOVEMENT_LIST_SUCCESS';
export const INGREDIENT_MOVEMENT_LIST_FAIL = 'INGREDIENT_MOVEMENT_LIST_FAIL';

export const INGREDIENT_MOVEMENT_DETAILS_REQUEST = 'INGREDIENT_MOVEMENT_DETAILS_REQUEST';
export const INGREDIENT_MOVEMENT_DETAILS_SUCCESS = 'INGREDIENT_MOVEMENT_DETAILS_SUCCESS';
export const INGREDIENT_MOVEMENT_DETAILS_FAIL = 'INGREDIENT_MOVEMENT_DETAILS_FAIL';

export const INGREDIENT_MOVEMENT_CREATE_REQUEST = 'INGREDIENT_MOVEMENT_CREATE_REQUEST';
export const INGREDIENT_MOVEMENT_CREATE_SUCCESS = 'INGREDIENT_MOVEMENT_CREATE_SUCCESS';
export const INGREDIENT_MOVEMENT_CREATE_FAIL = 'INGREDIENT_MOVEMENT_CREATE_FAIL';

export const INGREDIENT_MOVEMENT_UPDATE_REQUEST = 'INGREDIENT_MOVEMENT_UPDATE_REQUEST';
export const INGREDIENT_MOVEMENT_UPDATE_SUCCESS = 'INGREDIENT_MOVEMENT_UPDATE_SUCCESS';
export const INGREDIENT_MOVEMENT_UPDATE_FAIL = 'INGREDIENT_MOVEMENT_UPDATE_FAIL';

export const INGREDIENT_MOVEMENT_DELETE_REQUEST = 'INGREDIENT_MOVEMENT_DELETE_REQUEST';
export const INGREDIENT_MOVEMENT_DELETE_SUCCESS = 'INGREDIENT_MOVEMENT_DELETE_SUCCESS';
export const INGREDIENT_MOVEMENT_DELETE_FAIL = 'INGREDIENT_MOVEMENT_DELETE_FAIL';
