export const LAUNDRY_LIST_REQUEST = "LAUNDRY_LIST_REQUEST";
export const LAUNDRY_LIST_SUCCESS = "LAUNDRY_LIST_SUCCESS";
export const LAUNDRY_LIST_FAIL = "LAUNDRY_LIST_FAIL";
export const LAUNDRY_LIST_RESET = "LAUNDRY_LIST_RESET";

export const LAUNDRY_CREATE_REQUEST = "LAUNDRY_CREATE_REQUEST";
export const LAUNDRY_CREATE_SUCCESS = "LAUNDRY_CREATE_SUCCESS";
export const LAUNDRY_CREATE_FAIL = "LAUNDRY_CREATE_FAIL";

export const LAUNDRY_DETAILS_REQUEST = "LAUNDRY_DETAILS_REQUEST";
export const LAUNDRY_DETAILS_SUCCESS = "LAUNDRY_DETAILS_SUCCESS";
export const LAUNDRY_DETAILS_FAIL = "LAUNDRY_DETAILS_FAIL";
export const LAUNDRY_DETAILS_RESET = "LAUNDRY_DETAILS_RESET";

export const LAUNDRY_UPDATE_REQUEST = "LAUNDRY_UPDATE_REQUEST";
export const LAUNDRY_UPDATE_SUCCESS = "LAUNDRY_UPDATE_SUCCESS";
export const LAUNDRY_UPDATE_FAIL = "LAUNDRY_UPDATE_FAIL";
export const LAUNDRY_UPDATE_RESET = "LAUNDRY_UPDATE_RESET";

export const LAUNDRY_DELETE_REQUEST = "LAUNDRY_DELETE_REQUEST";
export const LAUNDRY_DELETE_SUCCESS = "LAUNDRY_DELETE_SUCCESS";
export const LAUNDRY_DELETE_FAIL = "LAUNDRY_DELETE_FAIL";
export const LAUNDRY_DELETE_RESET = "LAUNDRY_DELETE_RESET";
