export const PAID_ORDER_DETAILS_REQUEST = 'PAID_ORDER_DETAILS_REQUEST';
export const PAID_ORDER_DETAILS_SUCCESS = 'PAID_ORDER_DETAILS_SUCCESS';
export const PAID_ORDER_DETAILS_FAIL = 'PAID_ORDER_DETAILS_FAIL';