export const RESERVATION_STATISTICS_REQUEST = "RESERVATION_STATISTICS_REQUEST";
export const RESERVATION_STATISTICS_SUCCESS = "RESERVATION_STATISTICS_SUCCESS";
export const RESERVATION_STATISTICS_FAIL = "RESERVATION_STATISTICS_FAIL";
export const RESERVATION_STATISTICS_RESET = "RESERVATION_STATISTICS_RESET";

export const RESERVATION_LIST_REQUEST = "RESERVATION_LIST_REQUEST";
export const RESERVATION_LIST_SUCCESS = "RESERVATION_LIST_SUCCESS";
export const RESERVATION_LIST_FAIL = "RESERVATION_LIST_FAIL";
export const RESERVATION_LIST_RESET = "RESERVATION_LIST_RESET";

export const RESERVATION_CREATE_REQUEST = "RESERVATION_CREATE_REQUEST";
export const RESERVATION_CREATE_SUCCESS = "RESERVATION_CREATE_SUCCESS";
export const RESERVATION_CREATE_FAIL = "RESERVATION_CREATE_FAIL";
export const RESERVATION_CREATE_RESET = "RESERVATION_CREATE_RESET";

export const RESERVATION_DETAILS_REQUEST = "RESERVATION_DETAILS_REQUEST";
export const RESERVATION_DETAILS_SUCCESS = "RESERVATION_DETAILS_SUCCESS";
export const RESERVATION_DETAILS_FAIL = "RESERVATION_DETAILS_FAIL";
export const RESERVATION_DETAILS_RESET = "RESERVATION_DETAILS_RESET";

export const RESERVATION_UPDATE_REQUEST = "RESERVATION_UPDATE_REQUEST";
export const RESERVATION_UPDATE_SUCCESS = "RESERVATION_UPDATE_SUCCESS";
export const RESERVATION_UPDATE_FAIL = "RESERVATION_UPDATE_FAIL";
export const RESERVATION_UPDATE_RESET = "RESERVATION_UPDATE_RESET";

export const RESERVATION_DELETE_REQUEST = "RESERVATION_DELETE_REQUEST";
export const RESERVATION_DELETE_SUCCESS = "RESERVATION_DELETE_SUCCESS";
export const RESERVATION_DELETE_FAIL = "RESERVATION_DELETE_FAIL";
export const RESERVATION_DELETE_RESET = "RESERVATION_DELETE_RESET";

export const CLIENT_RESERVATIONS_REQUEST = 'CLIENT_RESERVATIONS_REQUEST';
export const CLIENT_RESERVATIONS_SUCCESS = 'CLIENT_RESERVATIONS_SUCCESS';
export const CLIENT_RESERVATIONS_FAIL = 'CLIENT_RESERVATIONS_FAIL';
